# Generated by Django 3.1.4 on 2021-01-09 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20210101_1642'),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
