# Generated by Django 3.1.4 on 2020-12-13 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.person')),
            ],
            bases=('iot.person',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('radius', models.FloatField(default=0.0)),
                ('account', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='iot.account')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.person')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{4}-\\d{4}$')])),
                ('account', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='iot.account')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.role')),
            ],
            bases=('iot.person',),
        ),
    ]
