# Generated by Django 3.1.4 on 2020-12-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_device_streetsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('NW', 'Not Working'), ('UM', 'Under Maintenance')], default='W', max_length=2),
        ),
    ]
