# Generated by Django 3.1.4 on 2020-12-16 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20201216_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 21, 36, 43, 608801, tzinfo=utc), verbose_name='date created'),
        ),
    ]
