# Generated by Django 3.1.4 on 2020-12-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20201213_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTranscript', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CO2Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2Level', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='InformationKiosk',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.device')),
            ],
            bases=('iot.device',),
        ),
        migrations.CreateModel(
            name='InputSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.device')),
            ],
        ),
        migrations.CreateModel(
            name='MicrofoneEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioTranscript', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThermometerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('inputsensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.inputsensor')),
            ],
            bases=('iot.inputsensor',),
        ),
        migrations.CreateModel(
            name='CO2Meter',
            fields=[
                ('inputsensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.inputsensor')),
            ],
            bases=('iot.inputsensor',),
        ),
        migrations.CreateModel(
            name='Microfone',
            fields=[
                ('inputsensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.inputsensor')),
            ],
            bases=('iot.inputsensor',),
        ),
        migrations.CreateModel(
            name='Thermometer',
            fields=[
                ('inputsensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.inputsensor')),
            ],
            bases=('iot.inputsensor',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='date created')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='date finalized')),
                ('InputSensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.inputsensor')),
            ],
        ),
    ]
