# Generated by Django 3.1.4 on 2020-12-15 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20201213_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 18, 21, 41, 190454, tzinfo=utc), verbose_name='date created'),
        ),
    ]
