# Generated by Django 3.1.4 on 2020-12-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_camera_cameraevent_co2event_co2meter_event_informationkiosk_inputsensor_microfone_microfoneevent_the'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Microfone',
            new_name='Microphone',
        ),
    ]
