# Generated by Django 3.1.4 on 2020-12-15 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20201215_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 18, 59, 4, 299181, tzinfo=utc), verbose_name='date created'),
        ),
    ]
