# Generated by Django 3.1.4 on 2020-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20201213_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicrofoneEvent',
            new_name='MicrophoneEvent',
        ),
    ]
