# Generated by Django 3.1.4 on 2020-12-13 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_auto_20201213_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='co2event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='microphoneevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='thermometerevent',
            name='id',
        ),
        migrations.AddField(
            model_name='cameraevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='co2event',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microphoneevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermometerevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iot.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 20, 50, 13, 381855, tzinfo=utc), verbose_name='date created'),
        ),
    ]
