from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator

# Create your models here.
class Account(models.Model):
    def __str__(self):
        return " account id " + str(self.id)

class City(models.Model):
    name = models.CharField(max_length=200)
    account = models.OneToOneField(Account, on_delete=models.CASCADE, editable=False)
    latitude = models.FloatField(default = 0.0)
    longitude = models.FloatField(default = 0.0)
    radius = models.FloatField(default = 0.0)

    def __str__(self):
        return self.name + " with account " + self.account.__str__() + " at lat " + str(self.latitude) + " and long " + str(self.longitude) + " with radius "+ str(self.radius)

# ------ People --------

class Role(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return "Role " + self.name

class Person(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    latitude = models.IntegerField(default = 0)
    longitude = models.IntegerField(default = 0)
    
    def __str__(self):
        return "Person at lat " + str(self.latitude) + " and long " + str(self.longitude)

class Resident(Person):
    account = models.OneToOneField(Account, on_delete=models.CASCADE, editable = False)
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=12,null=True, validators=[RegexValidator(r'^\d{2}-\d{4}-\d{4}$')])
    role = models.ForeignKey(Role, on_delete = models.CASCADE)
    
    def __str__(self):
        return "Resident with id "+ str(self.id) + " name " + self.name + " with account " + self.account.__str__() + " at lat " + str(self.latitude) + " and long " + str(self.longitude)

class Visitor(Person):
    
    def __str__(self):
        return "Visitor with id " + str(self.id) + " at lat " + str(self.latitude) + " and long " + str(self.longitude)

# ------ Devices --------
class Status(models.TextChoices):
    WORKING = 'W', 'Working'
    NOT_WORKING = 'NW', 'Not Working'
    UNDER_MAINTENANCE = 'UM', 'Under Maintenance'

class Device(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    account = models.OneToOneField(Account, on_delete=models.CASCADE, editable = False)
    latitude = models.FloatField(default = 0)
    longitude = models.FloatField(default = 0)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.WORKING)
    enabled = models.BooleanField()
    city = models.ForeignKey(City, on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return "Device id " + str(self.id) + " with account " + self.account.__str__() + " at lat " + str(self.latitude) + " and long " + str(self.longitude) + " with status "+ Status(self.status).label + " enabled " + str(self.enabled)

class StreetSign(Device):
    text = models.CharField(max_length= 200)

    def __str__(self):
        return "Street Sign " + super().__str__()

class InformationKiosk(Device):

    def purchase_ticket(self, event, person):
        # The Kiosk can also support purchasing tickets for concerts and other events.
        # check the event price
        # check if person has balance
        # charge person
        # emit event ticket to person
        raise NotImplementedError
    
    def __str__(self):
        return "Information Kiosk " + super().__str__()


# ------ Input sensors --------
class InputSensor(models.Model):
    # ABSTRACT CLASS - SHOULDN'T BE INSTANTIATED
    device = models.ForeignKey('Device', on_delete = models.CASCADE)
    def __str__(self):
        return " sensor with id " + str(self.id) + " at device " + str(self.device.__str__())

class Microphone(InputSensor):
    def __str__(self):
        return " Microphone "  + super().__str__()

class Thermometer(InputSensor):
    def __str__(self):
        return " Thermometer " + super().__str__()

class CO2Meter(InputSensor):
    def __str__(self):
        return " Co2 Meter " + super().__str__()

class Camera(InputSensor):
    def __str__(self):
        return " Camera " + super().__str__()

# ------ Events (generated by sensors) --------
class Event(models.Model):
    creation_date = models.DateTimeField('date created', default = timezone.now())
    finish_date = models.DateTimeField('date finalized', null=True)
    inputSensor = models.ForeignKey(InputSensor, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return " event created at " + str(self.creation_date) + " and finalized at " + str(self.finish_date)

class MicrophoneEvent(Event):
    # Django-Audiofield - https://pypi.org/project/django-audiofield/
    # audio = To be implemented
    audioTranscript = models.CharField(max_length= 200)
    def __str__(self):
        return " Microfone audio transcript " + self.audioTranscript + super().__str__()

class CameraEvent(Event):
    # ImageField https://www.geeksforgeeks.org/imagefield-django-models/
    # image = to be implemented
    imageTranscript = models.CharField(max_length= 200)
    def __str__(self):
        return " Camera image transcript "+ self.imageTranscript + super().__str__()

class ThermometerEvent(Event):
    temperature = models.FloatField(default=0.0)
    def __str__(self):
        return " Temperature " + str(self.temperature) + ' oC.' + super().__str__()

class CO2Event(Event):
    co2Level = models.FloatField(default=0.0)
    def __str__(self):
        return " CO2 level " + str(self.co2Level) + super().__str__()
