# Generated by Django 3.1.4 on 2021-01-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transaction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-updated',)},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
